version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    container_name: vector_db
    expose:
      - 6333:6333

  api:
    build: ./api
    container_name: api
    environment:
      - QDRANT_URL=http://qdrant:6333

  app:
    build: ./app
    depends_on:
      api:
        condition: service_completed_successfully
    ports:
      - "3000:3000"
    container_name: app
